### ISSUE TITLE
Build issues on Red Hat 7.3

### ISSUE THREAD

**Issue by ygrek** [SKS-Keyserver/sks-keyserver#53]
**[Original report](https://bitbucket.org/skskeyserver/sks-keyserver/issue/53) by Timothy Foreman (Bitbucket: [twforeman](https://bitbucket.org/twforeman), GitHub: [twforeman](https://github.com/twforeman)).**

----------------------------------------

I'm trying to build on Red Hat 7.3 and I'm having some issues.

First off, if I use OCaml 4.05 the `make all` step fails with:

    ocamlc -g -c -ccopt "-O -I/usr/include -DHAVE_ZLIB" stubs-sha3.c
    ocamlc -g -c -ccopt "-O -I/usr/include -DHAVE_ZLIB" stubs-md5.c
    stubs-md5.c:21:9: error: unknown type name ‘uint32’
             uint32 buf[4];
             ^
    stubs-md5.c:22:9: error: unknown type name ‘uint32’
             uint32 bits[2];
             ^
    make[1]: *** [stubs-md5.o] Error 2
    make[1]: Leaving directory `/home/vagrant/sks-1.1.6/cryptokit-1.7/src'
    make: *** [cryptokit-1.7/src/cryptokit.cma] Error 2

I found issue #49 that states you can't use OCaml 4.05, so I tried using OCaml 4.01.

It gets a lot further in the `make all` process, but fails with the following error:

    ocamlopt -I lib -I bdb -ccopt -L/usr/lib  -ccopt -Lbdb -dtypes  -inline 40 unix.cmxa str.cmxa bdb.cmxa nums.cmxa bigarray.cmxa cryptokit.cmxa -c update_subkeys.ml
    ocamlopt -I lib -I bdb -ccopt -L/usr/lib  -ccopt -Lbdb -dtypes  -inline 40 unix.cmxa str.cmxa bdb.cmxa nums.cmxa bigarray.cmxa cryptokit.cmxa -c sks_do.ml
    ocamlopt -I lib -I bdb -ccopt -L/usr/lib  -ccopt -Lbdb -dtypes  -inline 40 unix.cmxa str.cmxa bdb.cmxa nums.cmxa bigarray.cmxa cryptokit.cmxa -c unit_tests.ml
    ocamlc -I lib -I bdb -ccopt -L/usr/lib  -ccopt -Lbdb -dtypes  -g unix.cma str.cma bdb.cma nums.cma bigarray.cma cryptokit.cma -c sks.mli
    ocamlopt -I lib -I bdb -ccopt -L/usr/lib  -ccopt -Lbdb -dtypes  -inline 40 unix.cmxa str.cmxa bdb.cmxa nums.cmxa bigarray.cmxa cryptokit.cmxa -c sks.ml
    ocamlopt -o sks -I lib -I bdb -ccopt -L/usr/lib  -ccopt -Lbdb -dtypes  -inline 40 unix.cmxa str.cmxa bdb.cmxa nums.cmxa bigarray.cmxa cryptokit.cmxa crc.o pSet.cmx pMap.cmx utils.cmx heap.cmx mList.cmx mTimer.cmx mArray.cmx settings.cmx pstyle.cmx getfileopts.cmx common.cmx channel.cmx eventloop.cmx ehandlers.cmx bitstring.cmx meteredChannel.cmx number.cmx prime.cmx zZp.cmx rMisc.cmx linearAlg.cmx poly.cmx decode.cmx fqueue.cmx prefixTree.cmx msgContainer.cmx nbMsgContainer.cmx cMarshal.cmx reconMessages.cmx server.cmx client.cmx reconCS.cmx number_test.cmx decode_test.cmx poly_test.cmx Unique_time.cmx version.cmx packet.cmx parsePGP.cmx sStream.cmx bdbwrap.cmx key.cmx keyHash.cmx keyMerge.cmx fixkey.cmx fingerprint.cmx keydb.cmx armor.cmx dbMessages.cmx htmlTemplates.cmx wserver.cmx membership.cmx tester.cmx request.cmx stats.cmx index.cmx mRindex.cmx pTreeDB.cmx sendmail.cmx recvmail.cmx mailsync.cmx clean_keydb.cmx build.cmx fastbuild.cmx pbuild.cmx merge_keyfiles.cmx sksdump.cmx incdump.cmx dbserver.cmx reconComm.cmx recoverList.cmx catchup.cmx reconserver.cmx update_subkeys.cmx sks_do.cmx unit_tests.cmx sks.cmx
    /usr/bin/ld: cannot find -ldb-4.6
    collect2: error: ld returned 1 exit status
    File "caml_startup", line 1:
    Error: Error during linking
    make: *** [sks] Error 2

I can't figure out what that `-ldb-4.6` is referring to.
