### ISSUE TITLE
cryptokit 1.7 fails to build with ocaml < 3.12.1

### ISSUE THREAD

**Issue by ygrek** [SKS-Keyserver/sks-keyserver#24]
**[Original report](https://bitbucket.org/skskeyserver/sks-keyserver/issue/24) by Anonymous.**

----------------------------------------

using changeset 358:8b086323f5ef, I am unable to compile on CentOS 6.5.

[root@nocproj sks-keyserver]# make dep
ocamldep -pp camlp4o  *.mli *.ml > .depend
[root@nocproj sks-keyserver]# make all
tar xmvfz cryptokit-1.7.tar.gz
(SNIP)
...
(SNIP)
cd cryptokit-1.7/src && make all
make[1]: Entering directory `/root/src/sks-keyserver/cryptokit-1.7/src'
ocamlc -g -c -ccopt "-O -I/usr/include -DHAVE_ZLIB" rijndael-alg-fst.c
ocamlc -g -c -ccopt "-O -I/usr/include -DHAVE_ZLIB" stubs-aes.c
ocamlc -g -c -ccopt "-O -I/usr/include -DHAVE_ZLIB" d3des.c
ocamlc -g -c -ccopt "-O -I/usr/include -DHAVE_ZLIB" stubs-des.c
ocamlc -g -c -ccopt "-O -I/usr/include -DHAVE_ZLIB" arcfour.c
ocamlc -g -c -ccopt "-O -I/usr/include -DHAVE_ZLIB" stubs-arcfour.c
ocamlc -g -c -ccopt "-O -I/usr/include -DHAVE_ZLIB" sha1.c
ocamlc -g -c -ccopt "-O -I/usr/include -DHAVE_ZLIB" stubs-sha1.c
ocamlc -g -c -ccopt "-O -I/usr/include -DHAVE_ZLIB" sha256.c
ocamlc -g -c -ccopt "-O -I/usr/include -DHAVE_ZLIB" stubs-sha256.c
ocamlc -g -c -ccopt "-O -I/usr/include -DHAVE_ZLIB" ripemd160.c
ocamlc -g -c -ccopt "-O -I/usr/include -DHAVE_ZLIB" stubs-ripemd160.c
ocamlc -g -c -ccopt "-O -I/usr/include -DHAVE_ZLIB" blowfish.c
ocamlc -g -c -ccopt "-O -I/usr/include -DHAVE_ZLIB" stubs-blowfish.c
ocamlc -g -c -ccopt "-O -I/usr/include -DHAVE_ZLIB" keccak.c
ocamlc -g -c -ccopt "-O -I/usr/include -DHAVE_ZLIB" stubs-sha3.c
stubs-sha3.c:39: error: ‘custom_compare_ext_default’ undeclared here (not in a function)
make[1]: *** [stubs-sha3.o] Error 2
make[1]: Leaving directory `/root/src/sks-keyserver/cryptokit-1.7/src'
make: *** [cryptokit-1.7/src/cryptokit.cma] Error 2
[root@nocproj sks-keyserver]#
